Repository wecode-bootcamp-korea/18-1st-baemin-store-backend, pull requests merged in 2021-03, with the labels that each got.

#2 Feature/models
  baemin_store/settings.py
  order/__init__.py
  order/admin.py
  order/apps.py
  order/migrations/0001_initial.py
  order/migrations/0002_auto_20210318_1421.py
  order/migrations/__init__.py
  order/models.py
  order/tests.py
  order/views.py
  product/__init__.py
  product/admin.py
  product/apps.py
  product/migrations/0001_initial.py
  product/migrations/0002_review.py
  product/migrations/0003_product_product_option.py
  product/migrations/0004_auto_20210318_1420.py
  product/migrations/__init__.py
  product/models.py
  product/tests.py
  product/views.py
  user/__init__.py
  user/admin.py
  user/apps.py
  user/migrations/0001_initial.py
  user/migrations/0002_auto_20210317_1900.py
  user/migrations/0003_user_user_coupon.py
  user/migrations/0004_coupon_coupon_sub_category.py
  user/migrations/0005_user_name.py
  user/migrations/__init__.py
  user/models.py
  user/tests.py
  user/views.py
Labels: Status: 리뷰 요청

#4 [김택향] Sign up 기능 구현
  baemin_store/urls.py
  user/urls.py
  user/views.py
Labels: Status: Accepted

#9 [안다민] product 앱 models.py Option 테이블 컬럼 변경
  product/models.py
Labels: Status: Accepted

#3 [안다민] Login 기능 구현
  user/urls.py
  user/views.py
Labels: Status: 리뷰 요청

#11 [안다민] DB 마이그레이트(product.Models.py)(urgent)
  product/migrations/0005_auto_20210319_1552.py
Labels: Status: 리뷰 요청

#12 [안다민] product.models.py Option 마이그레이션 (urgent)
  product/migrations/0006_auto_20210319_1631.py
  product/migrations/0007_auto_20210319_1638.py
  product/models.py
Labels: Status: 리뷰 요청

#13 [안다민] models.py Product 테이블 수정(urgent)
  product/migrations/0008_product_stock.py
  product/models.py
Labels: Status: Accepted

#15 [안다민]models.py created_at, updated_at 추가 구현 + Cart, WishList 에 각각 product_option fk 추가 (urgent)
  order/migrations/0003_auto_20210321_1512.py
  order/models.py
  product/migrations/0009_auto_20210320_1645.py
  product/models.py
Labels: Status: 도움 요청, Status: 리뷰 요청

#16 [김택향] models.py Order 테이블 컬럼추가 (urgent)
  order/migrations/0004_auto_20210322_1611.py
  order/models.py
  product/migrations/0009_auto_20210320_1645.py
Labels: Status: 리뷰 요청

#8 [김택향] ProductView post()에 상품등록 기능 구현중
  baemin_store/urls.py
  product/urls.py
  product/views.py
Labels: Status: 리뷰 요청

#19 [김택향] auth_check, user_check decorator 생성
  utils/decorators.py
Labels: Status: 리뷰 요청

#14 [안다민] ProductshowView get()으로 등록 상품 가져와서 뿌려주는 기능 구현(프론트와 맞춤)
  baemin_store/urls.py
  product/urls.py
  product/views.py
Labels: Status: Accepted

#21 [김택향] ProductView get() Json body 에 key 값 추가 (urgent)
  product/views.py
Labels: Status: Accepted

#17 [안다민] order / veiws.py wishlist(찜하기) 구현(get&post)(프론트와 맞춤)(5차 리뷰 수정 완료)
  baemin_store/urls.py
  order/urls.py
  order/views.py
  user/urls.py
  user/views.py
Labels: Status: 리뷰 요청

#20 [김택향] 카테고리 별 상품목록 view 작성
  product/urls.py
  product/views.py
  utils/decorators.py
Labels: Status: Accepted

#22 [안다민] 쿠폰 기능 구현(주문 마치면 할 수 있게 프론트와 맞춰 보기 대기중)+conflict 수정
  baemin_store/urls.py
  order/urls.py
  order/views.py
  user/urls.py
  user/views.py
Labels: Status: 리뷰 요청

#24 [김택향] 카테고리 페이지 is_best, is_new, is_sale 키 값 추가 (urgent)
  product/views.py
  utils/util.py
Labels: Status: 리뷰 요청

#23 [김택향] 카트 담기/보여주기 & 결제페이지 물품선택/보여주기 & 장바구니 삭제
  order/urls.py
  order/views.py
  utils/decorators.py
Labels: Status: Accepted

#25 [김택향] 괄호 안닫힌거 닫음
  order/urls.py
Labels: Status: 리뷰 요청

#26 [김택향] 최종 에러 수정 및 csv 파일 집어넣는 파일 생성
  product/views.py
  user/views.py
  utils/auto_add.py
Labels: Status: 리뷰 요청

#27 [김택향] 결제정보 없을 때 장바구니 페이지 접근 에러해결
  order/views.py
  user/views.py
Labels: Status: 리뷰 요청

#28 [김택향] 데이터 넣는 view 로직 에러 수정
  product/views.py
  utils/auto_add.py
Labels: Status: 리뷰 요청
